<?php
class PDF extends FPDF
{	
	function rincian($dt_sts){
		foreach($dt_sts as $row){
			$retribusi = number_format($row->retribusi, 0, ",", ".");
			$denda = number_format($row->denda, 0, ",", ".");
			$tanda = number_format($row->tanda, 0, ",", ".");
			$total = number_format($row->total, 0, ",", ".");
			
			$this->setFont('ARIAL','B',12);
			$this->cell(190,5,'SURAT TANDA SETORAN',0,0,'C');
			$this->ln(5);
			
			$this->setFont('ARIAL','',10);
			$this->cell(20,5,'STS No : '.$row->no_sts,0,0,'L');
			$this->cell(120,5);
			$this->setFont('ARIAL','I',10);
			$this->cell(50,5,'Model  :  PK. 14',0,0,'R');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(65,10,'Harap diterima uang sebesar Rp. ',0,0,'L');
			$this->setFont('ARIAL','B',14);
			$this->cell(60,10,$total,1,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(60,8,'(dengan huruf)',0,0,'L');
			$this->cell(100,8,'('.$row->terbilang.' Rupiah)',0,0,'L');
			$this->ln();
			$this->cell(60,5,'Penerimaan :',0,0,'L');
			$this->ln();
			$this->setFont('ARIAL','B',10);
			$this->cell(50,8,'Kode Rekening',1,0,'C');
			$this->cell(100,8,'Uraian Rincian Obyek',1,0,'C');
			$this->cell(40,8,'Jumlah (Rp.)',1,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(50,5,'1.07.01.000.000.4.1.2.01.007','RL',0,'C');
			$this->cell(100,5,'a. Biaya Pengujian','RL',0,'L');
			$this->cell(10,5,'',0,0,'L');
			$this->cell(30,5,'','R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'1) JBB 0 s/d 2500 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb0, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'2) JBB 2501 s/d 5000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb1, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'3) JBB 5001 s/d 9000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb2, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'4) JBB di atas 9000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb3, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'','B',0,'L');
			$this->cell(95,5,'5) Kereta Gandeng / Tempelan ','B',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->jbb4, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(100,5,'b. Bukti Lulus Uji :','RL',0,'L');
			$this->cell(40,5,'','R',0,'L');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'1) Kartu Uji dan Tanda Uji ',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->tanda, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'','B',0,'L');
			$this->cell(95,5,'2) Kartu Uji dan Tanda Uji Hilang/Rusak ','B',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,'-','BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(100,5,'c. Biaya Denda','BRL',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->denda, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','BRL',0,'C');
			$this->cell(100,5,'d. Biaya Mutasi dan Numpang Uji Keluar Daerah','BRL',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->nuk, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->setFont('ARIAL','B',10);
			$this->cell(150,7,'TOTAL RETRIBUSI','BRL',0,'C');
			$this->cell(10,7,'Rp.','BL',0,'L');
			$this->cell(30,7,number_format($row->total, 0, ",", "."),'BR',0,'R');
			$this->ln(8);
			$this->setFont('ARIAL','',10);
			$this->cell(80,6,'',0,0,'L');
			$this->cell(110,6,'Uang tersebut diterima pada tanggal ....................................................',0,0,'L');
			
			$this->setFont('ARIAL','',10);
			$this->ln(8);
			$this->cell(60,5,'Cap Dinas / Unit Kerja',0,0,'C');
			$this->cell(60,5,'Penyetor',0,0,'C');
			$this->cell(60,5,'Kas Daerah',0,0,'C');
			$this->ln();
			$this->cell(120,5,'',0,0,'C');
			$this->cell(60,5,'Bendahara Umum Daerah',0,0,'C');
			$this->ln(18);
			$this->setFont('ARIAL','UB',10);
			$this->cell(60,5,'',0,0,'C');
			$this->cell(60,5,'S H O L E H',0,0,'C');
			$this->cell(60,5,'________________________',0,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(60,5,'',0,0,'C');
			$this->cell(60,5,'NIP. 19780107 201001 1 001',0,0,'C');
			$this->cell(60,5,'NIP. ........................................',0,0,'C');
			
			
			
			$this->ln(18);
			$this->setFont('ARIAL','B',12);
			$this->cell(190,5,'SURAT TANDA SETORAN',0,0,'C');
			$this->ln(5);
			
			$this->setFont('ARIAL','',10);
			$this->cell(20,5,'STS No : '.$row->no_sts,0,0,'L');
			$this->cell(120,5);
			$this->setFont('ARIAL','I',10);
			$this->cell(50,5,'Model  :  PK. 14',0,0,'R');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(65,10,'Harap diterima uang sebesar Rp. ',0,0,'L');
			$this->setFont('ARIAL','B',14);
			$this->cell(60,10,$total,1,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(60,8,'(dengan huruf)',0,0,'L');
			$this->cell(100,8,'('.$row->terbilang.' Rupiah)',0,0,'L');
			$this->ln();
			$this->cell(60,5,'Penerimaan :',0,0,'L');
			$this->ln();
			$this->setFont('ARIAL','B',10);
			$this->cell(50,8,'Kode Rekening',1,0,'C');
			$this->cell(100,8,'Uraian Rincian Obyek',1,0,'C');
			$this->cell(40,8,'Jumlah (Rp.)',1,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(50,5,'1.07.01.000.000.4.1.2.01.007','RL',0,'C');
			$this->cell(100,5,'a. Biaya Pengujian','RL',0,'L');
			$this->cell(10,5,'',0,0,'L');
			$this->cell(30,5,'','R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'1) JBB 0 s/d 2500 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb0, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'2) JBB 2501 s/d 5000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb1, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'3) JBB 5001 s/d 9000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb2, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'4) JBB di atas 9000 Kg',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->jbb3, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'','B',0,'L');
			$this->cell(95,5,'5) Kereta Gandeng / Tempelan ','B',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->jbb4, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(100,5,'b. Bukti Lulus Uji :','RL',0,'L');
			$this->cell(40,5,'','R',0,'L');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'',0,0,'L');
			$this->cell(95,5,'1) Kartu Uji dan Tanda Uji ',0,0,'L');
			$this->cell(10,5,'Rp.','L',0,'L');
			$this->cell(30,5,number_format($row->tanda, 0, ",", "."),'R',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(5,5,'','B',0,'L');
			$this->cell(95,5,'2) Kartu Uji dan Tanda Uji Hilang/Rusak ','B',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,'-','BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','RL',0,'C');
			$this->cell(100,5,'c. Biaya Denda','BRL',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->denda, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->cell(50,5,'','BRL',0,'C');
			$this->cell(100,5,'d. Biaya Mutasi dan Numpang Uji Keluar Daerah','BRL',0,'L');
			$this->cell(10,5,'Rp.','BL',0,'L');
			$this->cell(30,5,number_format($row->nuk, 0, ",", "."),'BR',0,'R');
			$this->ln();
			$this->setFont('ARIAL','B',10);
			$this->cell(150,7,'TOTAL RETRIBUSI','BRL',0,'C');
			$this->cell(10,7,'Rp.','BL',0,'L');
			$this->cell(30,7,number_format($row->total, 0, ",", "."),'BR',0,'R');
			$this->ln(8);
			$this->setFont('ARIAL','',10);
			$this->cell(80,6,'',0,0,'L');
			$this->cell(110,6,'Uang tersebut diterima pada tanggal ....................................................',0,0,'L');
			
			$this->setFont('ARIAL','',10);
			$this->ln(8);
			$this->cell(60,5,'Cap Dinas / Unit Kerja',0,0,'C');
			$this->cell(60,5,'Penyetor',0,0,'C');
			$this->cell(60,5,'Kas Daerah',0,0,'C');
			$this->ln();
			$this->cell(120,5,'',0,0,'C');
			$this->cell(60,5,'Bendahara Umum Daerah',0,0,'C');
			$this->ln(18);
			$this->setFont('ARIAL','UB',10);
			$this->cell(60,5,'',0,0,'C');
			$this->cell(60,5,'S H O L E H',0,0,'C');
			$this->cell(60,5,'________________________',0,0,'C');
			$this->ln();
			$this->setFont('ARIAL','',10);
			$this->cell(60,5,'',0,0,'C');
			$this->cell(60,5,'NIP. 19780107 201001 1 001',0,0,'C');
			$this->cell(60,5,'NIP. ........................................',0,0,'C');
			
			$this->Image(base_url().'files/ttd/ttd_sts.png',90,120,20,0,'PNG');
			$this->Image(base_url().'files/ttd/ttd_sts.png',90,280,20,0,'PNG');
		}
	}
}

$this->fpdf = new PDF("P","mm",array(210,330));
$this->fpdf->SetMargins(10,5,10); 
$this->fpdf->SetTitle($title);
$this->fpdf->AliasNbPages();
$this->fpdf->AddPage();
$this->fpdf->rincian($dt_sts);
$this->fpdf->Output("I",$title);
?>